Add user notifications
MiniaczQ/apsi pull request #95
Opened 2023-06-24 19:29 UTC by buczi

Blocked by backend missing API. Currently working on mocks. 
![image](https://github.com/MiniaczQ/apsi/assets/59873761/3e0bbe88-c3c7-40e1-bb3b-2dbb0144d178)

2023-06-25 13:59 UTC, Dove6 requested changes
Interesting approach. Wouldn't a drop-down menu be easier to implement?

2023-06-25 13:59 UTC, Dove6 commented on frontend/src/App.tsx
> +  }, [isLoggedIn, loginData, apiClient])
Push down to `RoutingRoot`.

2023-06-25 13:59 UTC, Dove6 commented on frontend/src/App.tsx
> +    const interval = setInterval(() => {
Live updates are not in scope of this task, no need to bother yourself with `setInterval`.

2023-06-25 13:59 UTC, Dove6 commented on frontend/src/notifications/Notifications.tsx
> +    };
Export from the original place instead of copy-pasting.

2023-06-25 13:59 UTC, Dove6 commented on frontend/src/notifications/Notifications.tsx
> +      </td>
Version ID isn't meaningful for users. Document name should be displayed instead.

2023-06-25 13:59 UTC, Dove6 commented on frontend/src/notifications/Notifications.tsx
> +        {notification.version.versionName}
There could be a hyperlink to the mentioned version.

2023-06-26 21:16 UTC, buczi commented on frontend/src/App.tsx
> +  }, [isLoggedIn, loginData, apiClient])
done.

2023-06-26 21:16 UTC, buczi commented on frontend/src/App.tsx
> +    const interval = setInterval(() => {
They are working not so badly so i will leave them.

2023-06-26 21:17 UTC, buczi commented on frontend/src/notifications/Notifications.tsx
> +    };
Moved to special element: StateBadge.

2023-06-26 21:17 UTC, buczi commented on frontend/src/notifications/Notifications.tsx
> +      </td>
Done.

2023-06-26 21:41 UTC, MortonPL requested changes
Got a couple of style issues and one actual concern regarding marking notifications as seen.

2023-06-26 21:41 UTC, MortonPL commented on frontend/src/models/StateBadge.tsx
> +  }
Files should end with an empty new line.

2023-06-26 21:41 UTC, MortonPL commented on frontend/src/models/Notification.ts
> +}
Files should end with an empty new line.

2023-06-26 21:41 UTC, MortonPL commented on frontend/src/api/BackendApiClient.ts
> +
```suggestion

```

2023-06-26 21:41 UTC, MortonPL commented on frontend/src/RoutingRoot.tsx
> +function RoutingRoot({ loginState, apiClient}: RoutingRootProps) {
```suggestion
function RoutingRoot({ loginState, apiClient }: RoutingRootProps) {
```

2023-06-26 21:41 UTC, MortonPL commented on frontend/src/RoutingRoot.tsx
> +      console.log() // Without this line interval check is not working
That sounds suspicious.

2023-06-26 21:41 UTC, MortonPL commented on frontend/src/App.tsx
> +}
```suggestion
};
```

2023-06-26 21:41 UTC, MortonPL commented on frontend/src/App.tsx
> -
Keep the empty new line.

2023-06-26 21:41 UTC, MortonPL commented on frontend/src/App.tsx
> +
```suggestion
```

2023-06-26 21:41 UTC, MortonPL commented on frontend/src/App.tsx
> +
```suggestion
```

No trailing white space.

2023-06-26 21:41 UTC, MortonPL commented on frontend/src/App.tsx
> +      <Route element={<RoutingRoot loginState={loginState} apiClient={apiClient}/>}>
```suggestion
      <Route element={<RoutingRoot loginState={loginState} apiClient={apiClient} />}>
```

2023-06-26 21:41 UTC, MortonPL commented on frontend/src/App.tsx
> +          <Route index path="/notifications" element={<Notifications apiClient={apiClient} loginState={loginState}/>}/>
```suggestion
          <Route index path="/notifications" element={<Notifications apiClient={apiClient} loginState={loginState} />}/>
```

2023-06-26 21:41 UTC, MortonPL commented on frontend/src/notifications/Notifications.tsx
> +}
```suggestion
}

```

2023-06-26 21:41 UTC, MortonPL commented on frontend/src/notifications/Notifications.tsx
> +    }
```suggestion
  }

```

2023-06-26 21:41 UTC, MortonPL commented on frontend/src/notifications/Notifications.tsx
> +        response.forEach(notification => apiClient.getVersion(notification.documentId,notification.versionId)
```suggestion
        response.forEach(notification => apiClient.getVersion(notification.documentId, notification.versionId)
```

2023-06-26 21:41 UTC, MortonPL commented on frontend/src/notifications/Notifications.tsx
> +      setNotifications(old => [...filteredNotifications,notification])
Isn't this async?

2023-06-26 21:41 UTC, MortonPL commented on frontend/src/notifications/Notifications.tsx
> +
```suggestion
```

2023-06-26 21:43 UTC, MortonPL commented
Also there are merge conflicts.

2023-06-26 21:45 UTC, MortonPL commented on frontend/src/notifications/Notifications.tsx
> +  const navigateToVersionInscpect = (documentId: string, versionId: string) => navigate(`/DocVer?documentId=${encodeURIComponent(documentId)}&versionId=${versionId}`);
```suggestion
  const navigateToVersionInspect = (documentId: string, versionId: string) => navigate(`/DocVer?documentId=${encodeURIComponent(documentId)}&versionId=${versionId}`);
```

Got a typo here.

2023-06-26 21:59 UTC, buczi commented on frontend/src/notifications/Notifications.tsx
> +      setNotifications(old => [...filteredNotifications,notification])
Can you expand on you thought?

2023-06-26 22:10 UTC, MortonPL commented on frontend/src/App.tsx
> +
Not unresolved, but whatever.

2023-06-26 22:10 UTC, MortonPL commented on frontend/src/notifications/Notifications.tsx
> +      setNotifications(old => [...filteredNotifications,notification])
`markAsRead` is async, so you need to wait for when it resolves. Currently you mark the notification as seen client-side regardless of the server response, I think.

2023-06-26 22:16 UTC, buczi commented on frontend/src/notifications/Notifications.tsx
> +      setNotifications(old => [...filteredNotifications,notification])
Fixed, for some reason i thought that you were talking about setNotifications and i was not sure what is wrong with it :sleepy:.

2023-06-26 22:19 UTC, MortonPL approved these changes

2023-06-26 22:20 UTC, Dove6 approved these changes

2023-06-26 22:21 UTC, MortonPL commented
Closes #33.

2023-06-26 22:25 UTC, merged